name: codemagic_tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  selectable_autolink_text:
    git:
      url: git@github.com:miyakeryo/flutter_selectable_autolink_text.git
      ref: "6650716ee93e910f96422e8e3bb7a9bcebd4b416"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
